### ISSUE TITLE
Merge issue

### ISSUE THREAD

**Issue by longp** [longp/Travel#34]
After merge the div columns overlapped, must have been an error when copy pasting

**Comment by Steph-harris** [comment]
I can't get the datepicker to work on anything smaller than a large screen either. And I just tried merging again from my copy that was working fine, but the master branch is still not working...

**Comment by longp** [comment]
maybe just delete the travel.html and add your travel.html that is correctly working. one of the Divs must have been misplaced when it merged so it put everything in a column it seems.

**Comment by longp** [comment]
or i might try and undo the initial merge

**Comment by longp** [comment]
I am able to fix up the merge issue, but that was for the previous changes you made. I dont know if this master branch was the most up to date one, you may have more changes you can merge into now.

**Comment by Steph-harris** [comment]
@longp Yay! This is looking really good and it is up to date with what I had.
